version: 2.1
jobs:
    build:
        machine: true
        steps:
            - checkout
            - add_ssh_keys:
                  fingerprints:
                      - "1e:4a:09:6d:64:a3:ab:5b:9c:76:d6:16:d1:9a:99:b8"
            - run:
                  name: build
                  command: |
                      set -x
                      ssh ${host} ${script}
workflows:
    build:
        jobs:
            - build:
              filters:
                  branches:
                      only: main
